### ISSUE TITLE
Please specify a PublicKey or PrivateKey instance

### ISSUE THREAD

**Issue by poetbydesign** [auth0-blog/spring-boot-auth#1]
I clone this project to get up and running, and immediately after running the server(mind you I touched nothing in the code) it crashed and gave me this error "Key bytes can only be specified for HMAC signatures. Please specify a PublicKey or PrivateKey instance".

**Comment by brunokrebs** [comment]
Hello @poetbydesign, this repository is intended to be used [while reading this blog post](https://auth0.com/blog/implementing-jwt-authentication-on-spring-boot/). I will add a README file explaining that. Thanks.
