### ISSUE TITLE
Error on Login

### ISSUE THREAD

**Issue by hendisantika** [auth0-blog/spring-boot-auth#2]
Nice repo.

I already follow your article in [dzone](https://dzone.com/articles/implementing-jwt-authentication-on-spring-boot-api)

But I have an error on login.
```
# logs into the application (JWT is generated)

curl -i -H "Content-Type: application/json" -X POST -d '{

    "username": "admin",

    "password": "password"

}' http://localhost:8080/login
```

It is said that : 
```
HTTP/1.1 401 
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Wed, 01 Nov 2017 21:58:46 GMT

{"timestamp":1509573525984,"status":401,"error":"Unauthorized","message":"Authentication Failed: result returns more than one elements; nested exception is javax.persistence.NonUniqueResultException: result returns more than one elements","path":"/login"}
```

Could you check my [repo](https://github.com/hendisantika/spring-boot-auth)?

So that you can check my error.

Thanks before.

**Comment by schuga** [comment]
hello hendisantika, 
I have got the same error
have you already solved this issue? 

best regards

**Comment by brunokrebs** [comment]
The error says `Authentication Failed: result returns more than one elements; nested exception is javax.persistence.NonUniqueResultException: result returns more than one elements`, so what your problem is (most likely) is that you have more than one user with the same username in your database.

**Comment by brunokrebs** [comment]
Try cleaning up your database or signing up with a new username then hitting login. I guess it will work. @schuga 

Please, comment what was the result.

**Comment by schuga** [comment]
hi brunokrebs, 
it works now. Thank you so much

**Comment by hendisantika** [comment]
Hallo @schuga, I still got the issue. But now different issue : 
```curl -i -H "Content-Type: application/json" -X POST -d '{
> 
>     "username": "admin",
> 
>     "password": "password"
> 
> }' http://localhost:8080/login
HTTP/1.1 401 
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Wed, 07 Feb 2018 23:29:15 GMT

{"timestamp":1518046155959,"status":401,"error":"Unauthorized","message":"Authentication Failed: Bad credentials","path":"/login"}
```

How did you solve previous issu @schuga ?

Any suggestion @brunokrebs ?

Thanks

**Comment by hendisantika** [comment]
Sorry, I already solved that.

**Comment by shivamnaik1001** [comment]
@hendisantika how did you solve it? I'm stuck with the same problem

**Comment by hendisantika** [comment]
What's is your issue @shivamnaik1001 ?
Can you tell me more details?
Thanks

**Comment by brunokrebs** [comment]
@shivamnaik1001, best way to ask for help is to share a sample that I (we) can run and check the issue... perhaps, you could share a GitHub repo?
